



# create user
###
POST https://multi-agents-production-aace.up.railway.app/api/v1/auth/register HTTP/1.1
content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

{
   "name":"Rozey kaziibwe",
  "email":"afli@gmail.com",
  "password":"123456",
  "phone":"0785557587",
  "role":"user"

}
###


# create user
###
POST https://multi-agents-production-aace.up.railway.app/api/v1/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

{
   "name":"Rozey kaziibwe",
  "email":"aine@gmail.com",
  "password":"123456",
  "phone":"0785557587",
  "role":"user", 
  "company_id":"67ac71d52103cc38e19928f7"

}
### admin, developer, user
###


###
# api to get all users
GET https://multi-agents-production-aace.up.railway.app/api/v1/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

###


###
# api to get single users
GET https://multi-agents-production-aace.up.railway.app/api/v1/users/67ab41f7995d9e1edc0fc1bb HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA




#  coleb and victor
###
POST https://multi-agents-production-aace.up.railway.app/api/v1/auth/login HTTP/1.1
content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

{
  "email":"admin@tubayoai.com",
  "password":"123456"
}
###



###
# get new access token and refresh token
POST https://multi-agents-production-aace.up.railway.app/api/v1/auth/token HTTP/1.1
content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsImlhdCI6MTc0MDk4ODY1Nn0.M7fuUy-ot4OhIoQvAZDH4L_zQ4u8IMp6DgcAPmsDwNc"
}
###


POST https://multi-agents-production-aace.up.railway.app/api/v1/auth/logout HTTP/1.1
content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWM3MWQ1MjEwM2NjMzhlMTk5MjhmOSIsIm5hbWUiOiJTc2VuZGVnZXlhIEFsYmVydCIsImlhdCI6MTczOTQzOTA3MSwiZXhwIjoxNzM5NDQwODcxfQ.kLUeWL4RW9YtC6ZGSPprE94IhzdGqkdXk0JwhruwmhI"
}
###




###
POST https://multi-agents-production-aace.up.railway.app/api/v1/company HTTP/1.1
content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

{
  
  "companyname":"Tubayo  ",
  "companyemail":"bobii@gmail.com ",
  "companylocation":"Nakawa ",
  "industry":"software enterprise",
  "name":"Ssendegeya Albert",
  "email":"bobii@gmail.com",
  "password":"123456",
  "phone":"0786567850",
  "role":"admin"

  
}
###

# get single company data
GET https://multi-agents-production-aace.up.railway.app/api/v1/company/67ac71d52103cc38e19928f7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

###


# get single company data
GET https://multi-agents-production-aace.up.railway.app/api/v1/company/67adc39652580f146cee9242 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

###

###
# get all companies

GET https://multi-agents-production-aace.up.railway.app/api/v1/company HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

###
PUT https://multi-agents-production-aace.up.railway.app/api/v1/company/67adc39652580f146cee9242 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

{
  
  "companyname":"Tubayo  ",
  "companyemail":"alfredo@gmail.com ",
  "companylocation":"Nakawa ",
  "industry":"software skdf"


  
}
###



###
# api to create agents
POST https://multi-agents-production-aace.up.railway.app/api/v1/agents HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

{

  "name":"TAI AI Agent",
  "description":"Helps with bookings on the tubayo website ",
  "title":"Powered by Tubayo",
  "status":"active"
}
###
















###
# api to get all agents
GET https://multi-agents-production-aace.up.railway.app/api/v1/agents HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

###


###
# api to get single agent
GET https://multi-agents-production-aace.up.railway.app/api/v1/agents/67aca2751cdcc2e11a6b217d HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA




###
# api to update agents
PUT https://multi-agents-production-aace.up.railway.app/api/v1/agents/67aca2751cdcc2e11a6b217d HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

{

  "name":"tiko 45krjt 3 ",
  "description":"we is to help impove marketing 24/7 support ",
  "title":"this to take it to the next level ",
  "status":"submited"
}
###


###
POST https://multi-agents-production-aace.up.railway.app/api/v1/purchasedagents HTTP/1.1
content-type: application/json 

{
  
  "companyname":"Tubayo  ",
  "companyemail":"rayo1@gmail.com ",
  "companylocation":"Nakawa ",
  "industry":"software enterprise",
  "name":"Ssendegeya Albert",
  "email":"rayo1@gmail.com",
  "password":"123456",
  "phone":"0786567850",
  "role":"admin",
  "plan" :"enterprise", 
  "amount":"5000",      
  "period":90,
  "agent_id":"67aca2751cdcc2e11a6b217d"
  
}
###



###
POST https://multi-agents-production-aace.up.railway.app/api/v1/purchasedagents/withacount HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA


{
  "company_id":"67adc39652580f146cee9242",
  "plan" :"enterprise", 
  "amount":"5000",      
  "period":90,
  "agent_id":"67af041ccd491cba04cf9278"
}
###


GET https://multi-agents-production-aace.up.railway.app/api/v1/purchasedagents/67ae5ee1c8bb70ec199f6bc3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

###

# api to get all purchased  agent
GET https://multi-agents-production-aace.up.railway.app/api/v1/purchasedagents/withcompayid/67c55bd3cd3a1f19e7341979 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

###
  POST https://multi-agents-production-aace.up.railway.app/api/v1/upload HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA


{
  "document" :"document", 
  "user_id":"67ab41f7995d9e1edc0fc1bb",      
  "company_id":"67ac6f7bc3f86a6b8a5b7533",
}
###
POST  https://multi-agents-production-aace.up.railway.app/api/v1/customerSupportQuery HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

{
  
  "query":"Experince tubayo online stores ",
  "company_id":"67c55bd3cd3a1f19e7341979",
  "agent_id":"67c56178cd3a1f19e734198a",
  "purchased_agent_id":"67c5619dcd3a1f19e7341990"


  
}


# get single query 
###
GET https://multi-agents-production-aace.up.railway.app/api/v1/customerSupportQuery/67b86a6a310245949cc1ce05 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

# update query

###
PUT  https://multi-agents-production-aace.up.railway.app/api/v1/customerSupportQuery/67b86a6a310245949cc1ce05 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

{
  
  "query":"what are there in the bag yes"
 

}



# get single query 
###
DELETE  https://multi-agents-production-aace.up.railway.app/api/v1/customerSupportQuery/67b86a6a310245949cc1ce05 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA

# get all query by the purchased agent id
###
GET https://multi-agents-production-aace.up.railway.app/api/v1/customerSupportQuery/withpurhasedid/67c5619dcd3a1f19e7341990 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU1YmQzY2QzYTFmMTllNzM0MTk3YiIsIm5hbWUiOiJBSSBBZG1pbiIsImlhdCI6MTc0MTAxMTgxOCwiZXhwIjoxNzQxMDEzNjE4fQ._B7mo0ieXJIv0TpZNh2vxWzWZYhF7LYRJH6nwr5PhUA
